export const docsConfig = [
  {
    title: 'Project Overview',
    items: [
      {
        title: 'Introduction',
        slug: 'introduction',
        icon: 'book',
        content: `
          <h1>🏆 xdcGotcha — The XDC Blockchain's First Persistent NFT Mood Agent</h1>
          
          <p>xdcGotcha is the XDC blockchain's first AI-powered NFT agent that analyzes wallet flows, mints dynamic NFTs, and expresses "mood" based on real on-chain behavior. Powered by a persistent, self-aware AI agent, xdcGotcha transforms wallets into living digital pets, giving every user a visual and narrative reflection of their wallet's financial health, trends, and emotional state.</p>

          <h2>Theme: XDC RWAi Agents</h2>
          
          <p>xdcGotcha is an autonomous AI agent for XDC that constantly analyzes wallet activity, tracks financial flows, and issues a living NFT that evolves its mood and story based on your on-chain performance. Every Gotchi NFT reflects real wallet inflows, outflows, and USD profit/loss, with on-chain pricing provided by GoPlugin oracles. AI-generated summaries and persistent memory make every Gotchi more than just a token—it's a personal, emotional dashboard for your blockchain life.</p>
        `
      },
      {
        title: 'How It Works',
        slug: 'how-it-works',
        icon: 'cpu',
        content: `
          <h2>🧠 How does it work?</h2>

          <h3>On-chain Analytics:</h3>
          <ul>
            <li>Scans every block for any XDC address, reconstructing monthly inflows and outflows</li>
            <li>Converts flows to USD using GoPlugin's XDC/USDT oracle, with historical accuracy</li>
          </ul>

          <h3>NFT Mood Engine:</h3>
          <ul>
            <li>Mints a Gotchi NFT for each wallet</li>
            <li>Updates the NFT's mood as wallet conditions change—using an agent logic based on inflow recency and net profit/loss</li>
          </ul>

          <h3>Autonomous AI Agent:</h3>
          <ul>
            <li>The agent schedules its own analysis, logs its thoughts, and keeps a running journal of every mood change and summary</li>
            <li>All summaries are generated by OpenAI GPT-4o, so the narrative evolves as your blockchain story unfolds</li>
          </ul>
        `
      }
    ]
  },
  {
    title: 'Features',
    items: [
      {
        title: 'Key Features',
        slug: 'features',
        icon: 'shield',
        content: `
          <h2>🌟 Key Features</h2>
          
          <h3>Real On-Chain Analysis</h3>
          <p>Full history, not just snapshots. Every trend, every anomaly, every dollar counted.</p>

          <h3>Persistent Memory</h3>
          <p>The agent remembers everything—it builds a full story, not just stats.</p>

          <h3>NFTs With Emotion</h3>
          <p>Gotchi NFTs visually and narratively represent your wallet's health. The mood updates itself—no user input required.</p>

          <h3>Plug-and-Play API</h3>
          <p>Frontend and dApp builders can display wallet mood, trends, and agent-generated summaries in real time.</p>

          <h3>Oracle-Powered USD Accounting</h3>
          <p>Every value is based on GoPlugin's real XDC/USDT price feed—no off-chain guesses.</p>

          <h3>AI-Powered Summaries</h3>
          <p>Every report is human-readable, clear, and expressive—thanks to GPT-4o.</p>
        `
      },
      {
        title: 'Mood System',
        slug: 'mood-system',
        icon: 'chart',
        content: `
          <h2>📊 How is mood determined?</h2>

          <ul>
            <li><strong>Excited:</strong> Inflow in the last 24h + net gain > $20</li>
            <li><strong>Happy:</strong> Inflow in last 3 days + net gain > $5</li>
            <li><strong>Content:</strong> Inflow in last week</li>
            <li><strong>Anxious:</strong> Inflow in last 7-30 days</li>
            <li><strong>Hungry:</strong> No inflow in 30+ days</li>
          </ul>

          <p>The agent checks these conditions for every wallet, every time it analyzes.</p>
        `
      }
    ]
  },
  {
    title: 'Technical Details',
    items: [
      {
        title: 'Architecture',
        slug: 'architecture',
        icon: 'settings',
        content: `
          <h2>🏗️ Architecture Overview</h2>

          <h3>Main Components:</h3>

          <h4>index2.js:</h4>
          <ul>
            <li>Core analytics engine</li>
            <li>Exposes /analyze endpoint for any wallet</li>
            <li>Handles block scanning, USD conversion, AI summary, and persistent caching</li>
          </ul>

          <h4>gotchiAgent.js:</h4>
          <ul>
            <li>Autonomous agent loop (runs forever, schedules its own analysis)</li>
            <li>Logs all events ("thoughts"), runs wallet/NFT mood logic, writes summaries</li>
          </ul>

          <h4>gotchiGuardian.js:</h4>
          <ul>
            <li>Contains the mood logic and NFT mint/update controller</li>
          </ul>

          <h4>priceAgent.js:</h4>
          <ul>
            <li>Handles live and historical price lookups from on-chain oracles</li>
          </ul>

          <h3>Persistent Memory:</h3>
          <p>All summaries, thoughts, and analytics are stored on disk for replay and history.</p>
        `
      },
      {
        title: 'API Reference',
        slug: 'api-reference',
        icon: 'cpu',
        content: `
          <h2>REST APIs</h2>

          <h3>Available Endpoints:</h3>
          <ul>
            <li><code>/api/summary</code> — View the agent's entire journal and history of all Gotchis</li>
            <li><code>/api/agent/analysis</code> — Latest wallet analysis for the agent</li>
            <li><code>/api/agent/thoughts</code> — The agent's persistent log of every thought, event, and AI action</li>
            <li><code>/api/price/current</code> — Live XDC/USD prices (agent-synced)</li>
            <li><code>/api/price/history?from=&to=</code> — Get price history in any range</li>
          </ul>
        `
      }
    ]
  }
];